name: Setup
description: Action that performs common setup tasks like setting up Java

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'jetbrains'
