name: Deploy

on:
  push:
    tags:
      # Gradle build logic relies on this tag format, so if you need to change it, you need to change
      # it there as well.
      - bom-*

env:
  GPG_KEY: ${{ secrets.ANDROID_GPG_KEY }}
  GPG_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.ANDROID_MAVEN_CENTRAL_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.ANDROID_MAVEN_CENTRAL_PASSWORD }}

jobs:
  # This job's steps must be synced with prePublishCheck Gradle task's checks to ensure that
  # we check required stuff on CI and at the same time developers can run the Gradle task to verify
  # their changes before publishing.
  preflight_checks:
    runs-on: macos-latest
    steps:
      # actions/checkout can't be included in the composite setup action, because the composite
      # action needs to be first checked out by the checkout action.
      - name: Check out code
        uses: actions/checkout@v5
        with:
          # Fetch all history including all tags, because we need previous release tag for verifyPublishing task
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Basic preflight checks
        uses: ./.github/actions/basic-preflight-check

      - name: Verify publishing
        run: ./gradlew verifyPublishing

      - name: Verify BOM version
        run: ./gradlew verifyBomVersion

      - name: Artifacts tests
        # We need to publish the latest versions to Maven local first before we can run tests
        # on published artifacts
        run: |
          ./gradlew publishToMavenLocal \
            -PsigningInMemoryKey=$GPG_KEY \
            -PsigningInMemoryKeyPassword=$GPG_PASSWORD \
            -PmavenCentralUsername=$MAVEN_USERNAME \
            -PmavenCentralPassword=$MAVEN_PASSWORD
          
          ./gradlew :app:testDebugUnitTest

  publish:
    needs: preflight_checks
    runs-on: macos-latest
    permissions:
      # Needed by softprops/action-gh-release to be able to create a release
      contents: write
    steps:
      # actions/checkout can't be included in the composite setup action, because the composite
      # action needs to be first checked out by the checkout action.
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Maven Central
        run: |
          ./gradlew --stacktrace publishAndReleaseToMavenCentral \
            -PsigningInMemoryKey=$GPG_KEY \
            -PsigningInMemoryKeyPassword=$GPG_PASSWORD \
            -PmavenCentralUsername=$MAVEN_USERNAME \
            -PmavenCentralPassword=$MAVEN_PASSWORD

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
